name: 'Create GitHub Release'
description: 'Create a GitHub release with packaged toolbox'

inputs:
  version_number:
    description: 'Version number for the release'
    required: true
  mltbx_path:
    description: 'Path to the MLTBX file'
    required: true
  source_directory:
    description: 'Directory containing source code'
    required: false
    default: 'src'

runs:
  using: "composite"
  steps:
    - name: Commit updated Contents.m file
      shell: bash
      continue-on-error: true
      env:
        SOURCE_DIRECTORY: ${{ inputs.source_directory }}
        VERSION_NUMBER: ${{ inputs.version_number }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git status
        find "$SOURCE_DIRECTORY" -type f -name Contents.m -exec git add {} +
        git commit -m "Final check-ins for release v${VERSION_NUMBER} [skip actions]"
        git fetch
        git push
        
    - name: Update tag
      shell: bash
      if: always()
      continue-on-error: true
      env:
        VERSION_NUMBER: ${{ inputs.version_number }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        tag_name="v${VERSION_NUMBER}"

        # Delete the existing tag locally if it exists
        if git tag -l "$tag_name" | grep -Fxq "$tag_name"; then
          echo "Deleting existing local tag $tag_name"
          git tag -d "$tag_name"
        else
          echo "Local tag $tag_name does not exist"
        fi
        
        # Delete the existing tag remotely if it exists
        if git ls-remote --tags origin | grep -Fq "refs/tags/$tag_name"; then
          echo "Deleting existing remote tag $tag_name"
          git push origin --delete "$tag_name"
        else
          echo "Remote tag $tag_name does not exist"
        fi
      
        # Create the tag with a message, including [skip actions] to prevent CI workflows
        git tag -a "$tag_name" -m "Release $tag_name [skip actions]"
      
        # Push the new tag to the remote repository
        git push origin "$tag_name"
        
    - name: Create GitHub release
      uses: ncipollo/release-action@v1
      with:
        draft: true        
        artifacts: "${{ inputs.mltbx_path }}"
        tag: "v${{ inputs.version_number }}"
        generateReleaseNotes: true
        body: "![MATLAB Versions Tested](https://img.shields.io/endpoint?url=https%3A%2F%2Fraw.githubusercontent.com%2F${{ github.repository }}%2Fgh-badges%2F.github%2Fbadges%2Fv${{ inputs.version_number }}%2Ftested_with.json)"
