name: 'Install MatBox'
description: 'Install MatBox in MATLAB on GitHub runner'
inputs:
  mode:  # mode of installation: release or commit, i.e install a released version or use latest commit
    description: 'Which installation mode to use'
    required: false
    default: 'release'
  version:
    description: 'MatBox version to install, e.g. "0.9.10". Only applies to release mode.'
    required: false
    default: 'latest'
runs:
  using: "composite"
  steps:
      - name: Install MatBox
        uses: matlab-actions/run-command@v3
        env:
           GITHUB_TOKEN: ${{ github.token }}
        with:
          command: |
            addpath( "${{ github.action_path }}" )
            installMatBox( "${{ inputs.mode }}", "${{ runner.temp }}/matbox", "Version", "${{ inputs.version }}" )

      - name: Confirm installation of MatBox
        uses: matlab-actions/run-command@v3
        with:
          command: |
            versionStr = matbox.toolboxversion();
            assert(~isempty(versionStr), 'Failed to install MatBox.');
