name: Run tests

on:
  workflow_call:
    inputs:
      matbox_version:
        description: MatBox version to install ("latest" or a specific version like "0.9.10").
        type: string
        default: 'latest'
      source_directory:
        type: string
        default: 'src'
        description: 'Directory containing source code'
      tests_directory:
        type: string
        default: 'tests'
        description: 'Directory containing MATLAB test suites'
      tools_directory:
        type: string
        default: 'tools'
        description: 'Directory containing tools'
      matlab_products:
        description: Optional list of MATLAB products to install.
        type: string
        default: ''
      needs_python:
        type: boolean
        default: false
        description: 'Whether Python is needed for testing (controls if Python versions are included in test matrix)'
      matrix_json:
        type: string
        required: true
        description: 'JSON string containing the test matrix from build-matrix job'
      needs_virtual_display:
        type: boolean
        default: false
        description: Whether to install virtual display for testing.
    
jobs:
  test:
    name: Run MATLAB tests (${{ matrix.MATLABVersion }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.matrix_json) }}

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        if: ${{ inputs.needs_python }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.pythonVersion }}

      # Install the virtual display before installing MATLAB
      - name: Start virtual display server
        if: ${{ inputs.needs_virtual_display }}
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> "$GITHUB_ENV"

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v3
        with:
          release: ${{ matrix.MATLABVersion }}
          products: ${{ inputs.matlab_products }}

      - name: Install MatBox
        uses: ehennestad/matbox-actions/install-matbox@v1.5
        with:
          version: ${{ inputs.matbox_version }}

      # Run all tests in the project.  Put results in a version specific subdirectory
      - name: Run tests
        uses: ehennestad/matbox-actions/test-code@v1.5
        with:
          source_directory: ${{ inputs.source_directory }}
          tests_directory: ${{ inputs.tests_directory }}
          tools_directory: ${{ inputs.tools_directory }}
          create_badge: false

      # Save the contents of the report directory from each release into an artifact.
      - name: Save report directory
        uses: actions/upload-artifact@v7
        if: always()
        with:
          # Specify MATLAB release in artifact name. This is used in a 
          # subsequent job to create a summary badge for the GitHub release page
          # using results across multiple MATLAB releases.
          name: reports-${{ matrix.MATLABVersion }}
          path: docs/reports
