name: Run tests

on:
  workflow_call:
    inputs:
      source_directory:
        description: Path to the directory containing code. Code coverage and code analysis will run on the contents of this folder and its subfolders.
        type: string
        default: 'src'
      tests_directory:
        type: string
        default: 'tests'
        description: 'Directory containing MATLAB test suites'
      tools_directory:
        description: Path to the directory containing CI tools or tests. Used for locating unit tests and running customized MatBox tasks.
        type: string
        default: 'tools'
      matlab_release:
        description: MATLAB release to use for running test suites and code analysis.
        type: string
        default: 'latest'
      matlab_use_cache:
        description: Whether to cache the MATLAB installation for faster subsequent setups.
        type: boolean
        default: false
      matlab_products:
        description: Optional list of MATLAB products to install.
        type: string
        default: ''
      needs_virtual_display:
        description: Whether to install virtual display for testing.
        type: boolean
        default: false

    secrets:
      CODECOV_TOKEN:
        required: false

jobs:
  # This workflow contains a single job called "test"
  test:
    name: Test toolbox code
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: # Assign secret to env to be able to use it in "if:" conditional below
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: Check out repository
        uses: actions/checkout@v4

      # Install the virtual display before installing MATLAB
      - name: Start virtual display server
        if: ${{ inputs.needs_virtual_display }}
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Set up MATLAB (${{ inputs.matlab_release }})
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ inputs.matlab_release }}
          cache: ${{ inputs.matlab_use_cache }}
          products: ${{ inputs.matlab_products }}

      - name: Install MatBox
        uses: ehennestad/matbox-actions/install-matbox@v1

      - name: Check code and upload report
        uses: ehennestad/matbox-actions/check-code@v1
        with:
          source_directory: ${{ inputs.source_directory }}
          tools_directory: ${{ inputs.tools_directory }}
      
      - name: Run tests
        uses: ehennestad/matbox-actions/test-code@v1
        with:
          source_directory: ${{ inputs.source_directory }}
          tests_directory: ${{ inputs.tests_directory }}
          tools_directory: ${{ inputs.tools_directory }}

      - name: Commit SVG badges if updated
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: ehennestad/matbox-actions/push-badges@v1
        with:
          pr-ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref_name }}
          pr-repo: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name || github.repository }}

      - name: Upload code coverage report to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ env.CODECOV_TOKEN != '' }}
        with:
          token: ${{ env.CODECOV_TOKEN }}
          files: docs/reports/codecoverage.xml

      - name: Save reports directory
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: docs/reports
